const mongoose = require('mongoose')

// Define an array of content fields
const contentFields = [
    'content1',
    'content2',
    'content3',
    'content4',
    'content5',
    'content6',
    'content7',
    'content8',
    'content9',
    'content10',
    'content11',
    'content12',
    'content13',
    'content14',
    'content15',
    'content16',
    'content17',
    'content18',
    'content19',
    'content20',
    'content21',
    'content22',
    'content23',
    'content24',
    'content25',
    'content26',
    'content27',
    'content28',
    'content29',
    'content30',
    'content31',
    'content32',
    'content33',
    'content34',
    'content35',
    'content36',
    'content37',
    'content38',
    'content39',
    'content40',
    'content41',
    'content42',
    'content43',
    'content44',
    'content45',
    'content46',
    'content47',
    'content48',
    'content49',
    'content50',
    'content51',
    'content52',
    'content53',
    'content54',
    'content55',
    'content56',
    'content57',
    'content58',
    'content59',
    'content60',
    'content61',
    'content62',
    'content63',
    'content64',
    'content65',
    'content66',
    'content67',
    'content68',
    'content69',
    'content70',
    'content71',
    'content72',
    'content73',
    'content74',
    'content75',
    'content76',
    'content77',
    'content78',
    'content79',
    'content80',
    'content81',
    'content82',
    'content83',
    'content84',
    'content85',
    'content86',
    'content87',
    'content88',
    'content89',
    'content90',
    'content91',
    'content92',
    'content93',
    'content94',
    'content95',
    'content96',
    'content97',
    'content98',
    'content99',
    'content100',
]

// Create an object with content fields and their types
const contentFieldsDefinition = contentFields.reduce((fields, field) => {
    fields[field] = String
    return fields
}, {})

const eightSchema = new mongoose.Schema(
    {
        ...contentFieldsDefinition,
        userId: {
            type: mongoose.Schema.Types.ObjectId,
            required: true,
        },
    },
    {
        timestamps: true,
    }
)

const EightModel = mongoose.model('Eight', eightSchema)

module.exports = EightModel
